import type { LucideIcon } from 'lucide-react'
import {
  Award,
  BookOpen,
  Briefcase,
  Cable,
  Calculator,
  CalendarClock,
  ChefHat,
  ContactRound,
  UserRound,
  Filter,
  MessageCircle,
  Megaphone,
  FileText,
  LayoutDashboard,
  Package,
  Percent,
  TrendingUp,
  PieChart,
  Gauge,
  Shield,
  Sparkles,
  Receipt,
  ShoppingBag,
  SlidersHorizontal,
  Store,
  Truck,
  Users,
  UtensilsCrossed,
  Wallet,
  Warehouse,
  Wrench,
  HandCoins,
  ClipboardCheck,
  Bike,
  KeyRound,
  Utensils,
  Hourglass,
  Gift,
  CalendarDays,
  Tags,
  Undo2,
  Factory,
  PackageCheck,
  WalletCards,
  RotateCcw,
  Recycle,
  Pill,
  HardHat,
  Repeat,
  Thermometer,
  Crown,
  BadgePercent,
  Bookmark,
  ShieldAlert,
  Wheat,
  PartyPopper,
  RefreshCcw,
  ScrollText,
  Wine,
  FlaskConical,
} from 'lucide-react'
import type { NavViewId } from '../navigation'
import { cn } from '../ui/cn'

const MAP: Record<NavViewId, LucideIcon> = {
  dash: LayoutDashboard,
  caisse: Wallet,
  catalogue: Package,
  stocks: Warehouse,
  comptabilite: Calculator,
  rh: Briefcase,
  crm: ContactRound,
  segmentation: Filter,
  whatsapp: MessageCircle,
  marketing: Megaphone,
  kitchen: ChefHat,
  ticketsFactures: Receipt,
  tables: UtensilsCrossed,
  promotions: Percent,
  loyalty: Award,
  onlineOrders: ShoppingBag,
  journal: BookOpen,
  personnel: Users,
  vendeuses: UserRound,
  pointage: CalendarClock,
  analytique: PieChart,
  rentabilite: TrendingUp,
  reporting: Gauge,
  controleInterne: Shield,
  evolutivite: Sparkles,
  integrations: Cable,
  parametres: SlidersHorizontal,
  network: Store,
  achats: Truck,
  devis: FileText,
  sav: Wrench,
  credits: HandCoins,
  inventairePhysique: ClipboardCheck,
  peremptions: Hourglass,
  livraisons: Bike,
  location: KeyRound,
  carte: Utensils,
  cadeaux: Gift,
  rdv: CalendarDays,
  tarifs: Tags,
  retoursFournisseur: Undo2,
  production: Factory,
  bl: PackageCheck,
  depenses: WalletCards,
  retoursClient: RotateCcw,
  consignes: Recycle,
  ordonnances: Pill,
  chantiers: HardHat,
  abonnements: Repeat,
  haccp: Thermometer,
  vip: Crown,
  commissions: BadgePercent,
  misesDeCote: Bookmark,
  pertes: ShieldAlert,
  allergenes: Wheat,
  evenements: PartyPopper,
  reprises: RefreshCcw,
  protocoles: ScrollText,
  cave: Wine,
  magistrales: FlaskConical,
}

export function NavIcon({
  id,
  className,
}: {
  id: NavViewId
  className?: string
}) {
  const Icon = MAP[id]
  return <Icon className={cn('h-7 w-7 shrink-0', className)} strokeWidth={1.75} />
}
