import type { BuiltinUserRole, StaffPermissions } from './types'

/** Permissions par défaut selon le rôle système. */
export const ROLE_DEFAULT_PERMISSIONS: Record<BuiltinUserRole, StaffPermissions> =
  {
    admin: {
      maxDiscountPct: 100,
      canViewDashboard: true,
      canViewAnalytique: true,
      canViewJournalReport: true,
      canManageCatalogFull: true,
      canEditPrices: true,
      canManageStocks: true,
      canDailyClosure: true,
      canProcessRefunds: true,
      canSwitchStore: true,
      canManagePersonnel: true,
      canViewTeamPointage: true,
      canConfigureStoresAdmin: true,
      canManageIntegrations: true,
      canConfigureAppSettings: true,
    },
    gerant: {
      maxDiscountPct: 20,
      canViewDashboard: true,
      canViewAnalytique: true,
      canViewJournalReport: true,
      canManageCatalogFull: true,
      canEditPrices: true,
      canManageStocks: true,
      canDailyClosure: true,
      canProcessRefunds: true,
      canSwitchStore: true,
      canManagePersonnel: false,
      canViewTeamPointage: true,
      canConfigureStoresAdmin: false,
      canManageIntegrations: false,
      canConfigureAppSettings: true,
    },
    caissier: {
      maxDiscountPct: 5,
      canViewDashboard: false,
      canViewAnalytique: false,
      canViewJournalReport: true,
      canManageCatalogFull: false,
      canEditPrices: false,
      canManageStocks: false,
      canDailyClosure: false,
      canProcessRefunds: false,
      canSwitchStore: false,
      canManagePersonnel: false,
      canViewTeamPointage: false,
      canConfigureStoresAdmin: false,
      canManageIntegrations: false,
      canConfigureAppSettings: false,
    },
    cuisinier: {
      maxDiscountPct: 0,
      canViewDashboard: false,
      canViewAnalytique: false,
      canViewJournalReport: false,
      canManageCatalogFull: false,
      canEditPrices: false,
      canManageStocks: false,
      canDailyClosure: false,
      canProcessRefunds: false,
      canSwitchStore: false,
      canManagePersonnel: false,
      canViewTeamPointage: false,
      canConfigureStoresAdmin: false,
      canManageIntegrations: false,
      canConfigureAppSettings: false,
    },
  }
